### ISSUE TITLE
How to add more than 4 chapters in huskydown

### ISSUE THREAD

**Issue by martinez-jorge** [benmarwick/huskydown#11]
Ben, 

I need some guidance on adding more than 4 chapters to my dissertation, which is 8 chapters. I tried using the same naming convention "04-chap4.Rmd" but I get an error saying the file "04-conclusion.Rmd" could not be found and was not knitted. I decided to leave "04-conclusion.Rmd" as is and kept "04-chap4.Rmd" but the fourth chapter does not produce after successful knitting. Please advise. Thank you!

**Comment by benmarwick** [comment]
Have you also updated your `_bookdown.yml` file with the file names of the new chapters?

This is the main configuration file for your thesis. It determines what Rmd files are included in the output, and in what order. Arrange the order of your chapters in this file and ensure that the names match the names in your folders.

**Comment by martinez-jorge** [comment]
Yep, that was it. Thank you!
