### ISSUE TITLE
Errors out when attempting to add captions to tables.

### ISSUE THREAD

**Issue by ccurtis7** [benmarwick/huskydown#12]
I just started adapting my thesis using huskydown, and I ran into some (probably newbie) errors when trying to add in my tables.

First, would it be possible to read in a table as an image (.png) rather than compiling using knitr if I am happy with the formatting?

Second, if that doesn't work, I have loaded my data for a table into a csv file and tried reading it in as specified in the huskydown docs. However, it errors out whenever I try to add in a caption:

```
! Missing $ inserted.
<inserted text> 
                $
l.786 \caption{(\#tab:size_colloids)testing}
                                            \\ 

Try to find the following text in thesis.Rmd:
  \caption{(\#tab:size_colloids)testing} 

You may need to add $ $ around a certain inline R expression `r ` in thesis.Rmd (see the above hint). See https://github.com/rstudio/rmarkdown/issues/385 for more info.
Error: Failed to compile thesis.tex. See https://yihui.name/tinytex/r/#debugging for debugging tips. See thesis.log for more info.
Please delete thesis.Rmd after you finish debugging the error.
```

This was generated using the following code block in an Rmd file:

```
{r size_colloids, echo=FALSE, results="asis"}
kable(size_colloids, format = 'latex', longtable = TRUE, booktabs = TRUE,
      caption = "test")
```

If I run it with the `caption` option, it works just fine.

Any help would be much appreciated.

**Comment by benmarwick** [comment]
I think the `_` in the `{r size_colloids, echo=FALSE, results="asis"}` might be the culprit here, related to [this issue](https://stackoverflow.com/a/12169234/1036500). Can you try `{r size-colloids, echo=FALSE, results="asis"}` and let me know what happens?

You could show an image of your table if you like, I'd use a chunk that has `knitr::include_graphics()` to show that image.

**Comment by ccurtis7** [comment]
I think I narrowed it down through trial and error. If I use the `select` command prior to trying to build a `kable` table, then it seems to work. I ended up using:

```
{r sizecolloids, results="asis", echo=FALSE}
size_colloids <- size_colloids %>%
  select(size,functionality,sizenm,ZP,PDI)
kable(size_colloids,
      col.names = c("Particle Size (nm)", "Surface Coating",
                    "Mean Hydrodynamic Diameter $\\pm$ SEM (nm)",
                    "Mean $\\zeta$-potential", "PDI $\\pm$ SEM"),
      caption = "Physicochemical characterization of PS nanoparticles including hydrodynamic diameter and $\\zeta$-potential in 10mM NaCl at 23°C. Data was collected via DLS and ZetaSizer (n=3). All values are reported as mean $\\pm$ standard error (SEM).",
      caption.short = "Physicochemical characterization of PS nanoparticles including hydrodynamic diameter and $\\zeta$-potential",
      longtable = TRUE,
      booktabs = TRUE,
      escape = FALSE) %>%
  column_spec(1:5, width="6em")
```

**Comment by benmarwick** [comment]
Thanks for the update, glad you got it sorted!
