### ISSUE TITLE
Change page margins for a single page within the thesis

### ISSUE THREAD

**Issue by ChrisWaloszek** [benmarwick/huskydown#16]
To be able to include very large tables, figures, or prints of external PDF files, it would be very helpful to be able to change the page margins for a single page (or even several) within the document.
Thereafter, the page margins should return to their default values. 
I tried to [seek advice at SO](https://stackoverflow.com/questions/62656467/bookdown-thesisdown-huskydown-change-page-margins-for-a-single-page-within-a-do), however without any success yet. Since the issue might be more related to `huskydown`/`thesisdown` than to `R-markdown`,  I though it might be better to place the inquiry here.

## What I tried:

In `template.tex` I added the following to be able to use landscape format:

      \usepackage{pdflscape} % to rotate pages, i.e switch to landscape format 
      \newcommand{\blandscape}{\begin{landscape}}
      \newcommand{\elandscape}{\end{landscape}}

And then tried the following within the main file, unfortunately without success

    ```{r echo=FALSE}
    vec <- c("Properties A", "Properties B")
    tab <- mtcars[1:3,1:4] %>% kable() %>% 
      kable_styling(latex_options = c("scale_down"))
    ```

    \blandscape
    ## 1. With out.width='XXX%'
    ```{r echo=FALSE, out.width='140%'}
    tab
    ```
    
    ## 2. "fullpage" as per uwthesis.cls
    \begin{fullpage}
    ```{r echo=FALSE}
    tab
    ```
    \end{fullpage}
    
    ## 3. "xtrafullpage" as per uwthesis.cls
    \begin{xtrafullpage} 
    ```{r echo=FALSE}
    tab
    ```
    \end{xtrafullpage}
    \elandscape
    
    ## 4. newgeometry as per SO recommendation to my post
    \newgeometry{left=1cm,right=1cm,top=1cm,bottom=1cm}
    ```{r echo=FALSE}
    tab
    ```
    \clearpage
    \restoregeometry
   
The first three attempts do not make any difference to the generated table. Its size remains the same.
The fourth one yields the following error:

    # ! Undefined control sequence.
    # l.190 \newgeometry
    #                   {left=1cm,right=1cm,top=1cm,bottom=1cm} 

Any advice/new feature on how to decrease the page margins/increase the area for tables, figures or PDFs temporarily within the document is greatly appreciated!

**Comment by benmarwick** [comment]
Looks like you good a pretty good answer on SO, so I'll close this for now.
