### ISSUE TITLE
Error when trying to render index.Rmd to PDF

### ISSUE THREAD

**Issue by AFSobral** [benmarwick/huskydown#18]
Hi there, first of all, let me thank for providing this template :)
I am getting an error, after following your initial guidelines, when I try to render the thesis into a PDF, by opening the index.Rmd file in RStudio and clicking the "knit" button. I get the following error:

"output file: thesis.knit.md

! Undefined control sequence.
<argument> ...}}\NormalTok { pkg[}\SpecialCharTok 
                                                  {!}\NormalTok {(pkg }\Spec...
l.353 ...onTok{installed.packages}\NormalTok{())]}

Error: LaTeX failed to compile thesis.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See thesis.log for more info.
In addition: Warning messages:
1: replacing previous import ‘dplyr::pull’ by ‘git2r::pull’ when loading ‘huskydown’ 
2: In has_crop_tools() : 
Tool(s) not installed or not in PATH: pdfcrop, ghostcript
-> As a result, figure cropping will be disabled.
Execution halted"

I am doing this right after I choose to start a new document with the husky down template.
Hope you can help.
Best,
Ana

**Comment by ismayc** [comment]
Can you check under `fig_crop` [here](https://bookdown.org/yihui/rmarkdown/pdf-document.html#figure-options-1)? It looks like you'll need to install both `pdfcrop` and `ghostscript` to get the halted execution to go away. Please do tag me here with @ismayc if you need further assistance!

**Comment by AFSobral** [comment]
Thank you for the quick reply @ismayc!
I was able to solve the warning related to pdfcrop and Ghostscript since I created this issue.
However I am still not able to render the pdf.
Please find the details below.
Thank you dor your help!

**When I try to render index.Rmd file I get the following:**

processing file: thesis.Rmd
|... | 5%
ordinary text without R code

|....... | 10%
label: include_packages (with options)
List of 1
$ include: logi FALSE

|.......... | 14%
ordinary text without R code

|............. | 19%
label: load (with options)
List of 1
$ echo: logi FALSE

|................. | 24%
ordinary text without R code

|.................... | 29%
label: str
|....................... | 33%
ordinary text without R code

|........................... | 38%
label: load_pkgs (with options)
List of 2
$ echo : logi FALSE
$ message: logi FALSE

|.............................. | 43%
ordinary text without R code

|................................. | 48%
label: speciesinfo (with options)
List of 2
$ echo : logi FALSE
$ results: chr "asis"

|..................................... | 52%
ordinary text without R code

|........................................ | 57%
label: include_packages_2 (with options)
List of 1
$ include: logi FALSE

|........................................... | 62%
inline R code fragments

|............................................... | 67%
label: unnamed-chunk-1 (with options)
List of 3
$ ref.label: chr "include_packages"
$ results : chr "hide"
$ echo : logi TRUE

|.................................................. | 71%
ordinary text without R code

|..................................................... | 76%
label: unnamed-chunk-2 (with options)
List of 3
$ ref.label: chr "include_packages_2"
$ results : chr "hide"
$ echo : logi TRUE

|......................................................... | 81%
inline R code fragments

|............................................................ | 86%
label: unnamed-chunk-3 (with options)
List of 2
$ echo: logi FALSE
$ eval: logi FALSE

|............................................................... | 90%
ordinary text without R code

|................................................................... | 95%
label: unnamed-chunk-4 (with options)
List of 1
$ echo: logi FALSE

|......................................................................| 100%
ordinary text without R code

/Applications/RStudio.app/Contents/MacOS/pandoc/pandoc +RTS -K512m -RTS thesis.utf8.md --to latex --from markdown+autolink_bare_uris+tex_math_single_backslash --output thesis.tex --lua-filter /Library/Frameworks/R.framework/Versions/4.0/Resources/library/bookdown/rmarkdown/lua/custom-environment.lua --lua-filter /Library/Frameworks/R.framework/Versions/4.0/Resources/library/rmarkdown/rmarkdown/lua/pagebreak.lua --lua-filter /Library/Frameworks/R.framework/Versions/4.0/Resources/library/rmarkdown/rmarkdown/lua/latex-div.lua --metadata-file /var/folders/nf/myc19xfn73z5hkt484xs3xk80000gn/T//RtmpWNFaC3/filee8fc4afe9c74 --self-contained --table-of-contents --toc-depth 3 --template template.tex --number-sections --highlight-style tango --pdf-engine pdflatex --wrap preserve --top-level-division=chapter --include-in-header /var/folders/nf/myc19xfn73z5hkt484xs3xk80000gn/T//RtmpWNFaC3/rmarkdown-stre8fc6a593530.html --variable tables=yes --standalone -Mhas-frontmatter=false --citeproc
output file: thesis.knit.md

This is pdfTeX, Version 3.14159265-2.6-1.40.21 (TeX Live 2020) (preloaded format=pdflatex)
restricted \write18 enabled.
entering extended mode

! Emergency stop.
<read *>

Error: LaTeX failed to compile thesis.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See thesis.log for more info.
In addition: Warning message:
replacing previous import ‘dplyr::pull’ by ‘git2r::pull’ when loading ‘huskydown’
Execution halted

**Thesis.log as the following info:**

XeTeX is required to compile this document.
Sorry!
! Emergency stop.
<read *>

l.10 \RequireXeTeX

Here is how much of TeX's memory you used:
3330 strings out of 480608
42827 string characters out of 5903630
285571 words of memory out of 5000000
19191 multiletter control sequences out of 15000+600000
532636 words of font info for 25 fonts, out of 8000000 for 9000
1141 hyphenation exceptions out of 8191
38i,0n,49p,921b,36s stack positions out of 5000i,500n,10000p,200000b,80000s

! ==> Fatal error occurred, no output PDF file produced!

**Session info:**

xfun::session_info('rmarkdown')
R version 4.0.4 (2021-02-15)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 10.16, RStudio 1.4.1106

Locale: en_US.UTF-8 / en_US.UTF-8 / en_US.UTF-8 / C / en_US.UTF-8 / en_US.UTF-8

Package version:
base64enc_0.1.3 digest_0.6.27 evaluate_0.14 glue_1.4.2
graphics_4.0.4 grDevices_4.0.4 highr_0.8 htmltools_0.5.1.1
jsonlite_1.7.2 knitr_1.31 magrittr_2.0.1 markdown_1.1
methods_4.0.4 mime_0.10 rlang_0.4.10 rmarkdown_2.7.2
stats_4.0.4 stringi_1.5.3 stringr_1.4.0 tinytex_0.30.1
tools_4.0.4 utils_4.0.4 xfun_0.22 yaml_2.2.1

Pandoc version: 2.11.4

**Comment by ismayc** [comment]
Ah! I misunderstood. It looks like you need a different form of LaTeX than the default. You can change that in RStudio [globally or for a project](https://support.rstudio.com/hc/en-us/articles/200532257-Customizing-LaTeX-Options?mobile_site=true) or directly [in the YAML](https://bookdown.org/yihui/rmarkdown-cookbook/latex-unicode.html) of your thesis.

**Comment by AFSobral** [comment]
That was what I thought, unfortunately I have tried both of the options and I still get the error...

The YAML has:
"output: 
huskydown::thesis_pdf: 
latex_engine: xelatex"

RStudio is also set to use knit and XeLatex.

However for some reason when I try to render the file I get:

"This is pdfTeX, Version 3.14159265-2.6-1.40.21 (TeX Live 2020) (preloaded format=pdflatex)"

I have tried it with TinyTex and MacTex as well and still nothing works...

Could it have something to do with Pandoc?
Thank you @ismayc!

**Comment by ismayc** [comment]
Unfortunately, I'm getting a similar error when I try to build the default template with {huskydown}. If you aren't a UW student (I'm not sure if you are), I have needed to make a couple updates recently to the {thesisdown} template to get it to work with pandoc changes and I'm not sure if {huskydown} is up-to-date with these. If you install the latest version of {thesisdown} with `remotes::install_github("ismayc/thesisdown", ref = "develop")` in R, you can create a New RStudio project using the thesisdown template and then try that out? I hate to have you switch your flow, but that might be the best option here.

**Comment by benmarwick** [comment]
Hi @AFSobral, I think I've now pulled in the critical updates mentioned by @ismayc (thank you for dropping in here!). I can build the PDF on my computer and the PDF is also built on the CI (https://travis-ci.org/github/benmarwick/huskydown). Please update your version of the pkg, and open an new issue here if you encounter problems.

**Comment by AFSobral** [comment]
@benmarwick and @ismayc, thank you very much for your help.
I will check this today and will let you know!

**Comment by AFSobral** [comment]
Hi @benmarwick,
I confirm I was able to render the PDF.
However it looks very different in terms of layout, not sure if you are aware of that.
Please see picture below.
<img width="1679" alt="Screenshot 2021-03-30 at 16 59 46" src="https://user-images.githubusercontent.com/79585840/113019770-da089d00-9179-11eb-81f2-e92c1f8f749a.png">
