### ISSUE TITLE
Failed to Compile Thesis Error on Mac OSX

### ISSUE THREAD

**Issue by mrworthington** [benmarwick/huskydown#4]
Hey!

##Description of Erorr
Was playing around with Huskydown, trying to get it work. Followed the instructions you provided for PDFs (naming `index.Rmd`), but keep getting the error below. As a note, I've tried deleting `thesis.Rmd` 

In addition, I have ensured I'm running the full install of MacTex 2017 and have ensured all of the packages in TexLive are installed and updated. That said, I'm not sure why this error is occurring and was wondering if you had seen this error before: 

## Error Language from RStudio Console

`Error: Failed to compile thesis.tex. See thesis.log for more info. Please delete thesis.Rmd after you finish debugging the error. Execution halted`

## Error Language From `thesis.log` File

​

> .................................................
> 
> . fontspec info: "no-scripts"
> . 
> . Font "EB Garamond" does not contain any OpenType `Script' information.
> .................................................
> 
> ------
> 
> - fontspec warning: "aat-feature-not-exist-in-font"
> - 
> - AAT feature 'Numbers=Proportional' (6,1) not available in font 'EB
> - Garamond'.
> 
> ------
> 
> \g__fontspec_family_EBGaramond_int=\count266
> .................................................
> . fontspec info: "no-font-shape"
> . 
> . Could not resolve font "EB Garamond/BI" (it probably doesn't exist).
> .................................................
> .................................................
> . fontspec info: "no-font-shape"
> . 
> . Could not resolve font "EB Garamond/B" (it probably doesn't exist).
> .................................................
> .................................................
> . fontspec info: "no-font-shape"
> . 
> . Could not resolve font "EB Garamond/I" (it probably doesn't exist).
> .................................................
> 
> ------
> 
> - fontspec warning: "aat-feature-not-exist-in-font"
> - 
> - AAT feature 'Numbers=Proportional' (6,1) not available in font 'EB
> - Garamond'.
> 
> ------
> 
> .................................................
> . fontspec info: "defining-font"
> . 
> . Font family 'EBGaramond(0)' created for font 'EB Garamond' with options
> . [Numbers={Proportional}].
> .  
> .  This font family consists of the following NFSS series/shapes:
> .  
> . - 'normal' (m/n) with NFSS spec.: <->"EB Garamond/AAT"
> . - 'small caps'  (m/sc) with NFSS spec.: 
> .................................................
> \symDigits:m:n=\mathgroup6
> .................................................
> . fontspec info: "no-scripts"
> . 
> . Font "EB Garamond" does not contain any OpenType `Script' information.
> .................................................
> 
> ------
> 
> - fontspec warning: "aat-feature-not-exist-in-font"
> - 
> - AAT feature 'Numbers=Proportional' (6,1) not available in font 'EB
> - Garamond'.
> 
> ------
> 
> \symLatin:m:n=\mathgroup7
> \symLatin:m:it=\mathgroup8
> .................................................
> . fontspec info: "no-scripts"
> . 
> . Font "EB Garamond" does not contain any OpenType `Script' information.
> .................................................
> 
> ------
> 
> - fontspec warning: "aat-feature-not-exist-in-font"
> - 
> - AAT feature 'Numbers=Proportional' (6,1) not available in font 'EB
> - Garamond'.
> 
> ------
> 
> \symGreek:m:n=\mathgroup9
> \symGreek:m:it=\mathgroup10
> .................................................
> . fontspec info: "no-scripts"
> . 
> . Font "EB Garamond" does not contain any OpenType `Script' information.
> .................................................
> .................................................
> . fontspec info: "no-font-shape"
> . 
> . Could not resolve font "EB Garamond/BI" (it probably doesn't exist).
> .................................................
> .................................................
> . fontspec info: "no-font-shape"
> . 
> . Could not resolve font "EB Garamond/B" (it probably doesn't exist).
> .................................................
> .................................................
> . fontspec info: "no-font-shape"
> . 
> . Could not resolve font "EB Garamond/I" (it probably doesn't exist).
> .................................................
> .................................................
> . fontspec info: "defining-font"
> . 
> . Font family 'EBGaramond(1)' created for font 'EB Garamond' with options [].
> .  
> .  This font family consists of the following NFSS series/shapes:
> .  
> . - 'normal' (m/n) with NFSS spec.: <->"EB Garamond/AAT"
> . - 'small caps'  (m/sc) with NFSS spec.: 
> .................................................
> LaTeX Font Info:    Redeclaring math alphabet \mathrm on input line 912.
> LaTeX Font Info:    Overwriting math alphabet `\mathrm' in version `bold'
> (Font)                  TU/EBGaramond(1)/m/n --> TU/EBGaramond(1)/bx/n on input
>  line 912.
> LaTeX Font Info:    Redeclaring math alphabet \mathit on input line 912.
> LaTeX Font Info:    Overwriting math alphabet `\mathit' in version `normal'
> (Font)                  OT1/cmr/m/it --> TU/EBGaramond(1)/m/it on input line 91
> 2.
> LaTeX Font Info:    Overwriting math alphabet `\mathit' in version `bold'
> (Font)                  OT1/cmr/bx/it --> TU/EBGaramond(1)/m/it on input line 9
> 12.
> LaTeX Font Info:    Redeclaring math alphabet \mathbf on input line 912.
> LaTeX Font Info:    Overwriting math alphabet `\mathbf' in version `normal'
> (Font)                  OT1/cmr/bx/n --> TU/EBGaramond(1)/bx/n on input line 91
> 2.
> LaTeX Font Info:    Overwriting math alphabet `\mathbf' in version `bold'
> (Font)                  OT1/cmr/bx/n --> TU/EBGaramond(1)/bx/n on input line 91
> 2.
> LaTeX Font Info:    Overwriting math alphabet `\mathit' in version `bold'
> (Font)                  TU/EBGaramond(1)/m/it --> TU/EBGaramond(1)/bx/it on inp
> ut line 912.
> \symOperators:m:n=\mathgroup11
> .................................................
> . fontspec info: "no-scripts"
> . 
> . Font "EB Garamond" does not contain any OpenType `Script' information.
> .................................................
> .................................................
> . fontspec info: "no-font-shape"
> . 
> . Could not resolve font "EB Garamond/BI" (it probably doesn't exist).
> .................................................
> .................................................
> . fontspec info: "no-font-shape"
> . 
> . Could not resolve font "EB Garamond/B" (it probably doesn't exist).
> .................................................
> .................................................
> . fontspec info: "no-font-shape"
> . 
> . Could not resolve font "EB Garamond/I" (it probably doesn't exist).
> .................................................
> .................................................
> . fontspec info: "defining-font"
> . 
> . Font family 'EBGaramond(2)' created for font 'EB Garamond' with options
> . [Mapping=tex-text,RawFeature={c2sc,scmp}].
> .  
> .  This font family consists of the following NFSS series/shapes:
> .  
> . - 'normal' (m/n) with NFSS spec.: <->"EB
> . Garamond/AAT:c2sc,scmp;mapping=tex-text;"
> . - 'small caps'  (m/sc) with NFSS spec.: 
> .................................................
> .................................................
> . fontspec info: "no-scripts"
> . 
> . Font "EB Garamond" does not contain any OpenType `Script' information.
> .................................................
> 
> ------
> 
> - fontspec warning: "aat-feature-not-exist-in-font"
> - 
> - AAT feature 'Numbers=OldStyle' (21,0) not available in font 'EB Garamond'.
> 
> ------
> 
> !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
> !
> ! LaTeX error: "kernel/key-choice-unknown"
> ! 
> ! Key 'fontspec-aat/Contextuals' accepts only a fixed set of choices.
> ! 
> ! See the LaTeX3 documentation for further information.
> ! 
> ! For immediate help type H <return>.
> !...............................................  
>                                                   
> l.919 ...ternate, Ligatures={Common}]{EB Garamond}
>                                                    
> Here is how much of TeX's memory you used:
>  13009 strings out of 492998
>  274667 string characters out of 6134491
>  355323 words of memory out of 5000000
>  16909 multiletter control sequences out of 15000+600000
>  530312 words of font info for 27 fonts, out of 8000000 for 9000
>  1348 hyphenation exceptions out of 8191
>  47i,0n,82p,10522b,233s stack positions out of 5000i,500n,10000p,200000b,80000s
> 
> No pages of output.

**Comment by benmarwick** [comment]
Thanks for your note, are you sure that you have the EBGaramond font installed? 

I get it from here: https://github.com/georgd/EB-Garamond

**Comment by mrworthington** [comment]
I checked this morning. On macs, you load them through MacTex's TexLive Utility. Not sure how it's done on Windows. Anyway, here's a screenshot showing I've got it installed. 

<img width="1023" alt="screen shot 2017-09-28 at 3 10 36 pm" src="https://user-images.githubusercontent.com/8171106/30988240-548b5272-a45f-11e7-926e-9b8b75491d33.png">

**Comment by benmarwick** [comment]
Righto, thanks for the update. I think the font might need to be available at the system level, for example, do you have EBGaramond available in lists of fonts in other software on your computer, such as in a word processor?

We're using xelatex here, such that it looks for the required fonts among your system fonts.

In a linux environment I do `sudo apt-get install fonts-ebgaramond -y` and that sorts it out.  On OSX can you download them from https://github.com/georgd/EB-Garamond, unzip and drag and drop onto the system fonts folder?

**Comment by mrworthington** [comment]
So, **1)** forgot that fontspec uses system fonts, so I installed it. But **2)** I'm still getting the same error. Wanna give it a try on a Mac Platform on your end and let me know if you're able to replicate the error? I'm looking at this and scratching my head.

**Comment by benmarwick** [comment]
I don't have an OSX machine handy, but I'm [currently experimenting](https://travis-ci.org/benmarwick/huskydown/builds) with this pkg and the Travis-CI OSX build service. I can't reproduce your error yet, but still trying (the CI service is very slow). 

Please do take a look at the [Travis-CI config](https://github.com/benmarwick/huskydown/blob/master/.travis.yml) in case some of the setup there solves your problem. If you install the fonts with brew that might solve your EB Garamond problem?

**Comment by benmarwick** [comment]
I've now made a PDF using this pkg in OSX on Travis-CI (here's the [log](https://travis-ci.org/benmarwick/huskydown/builds/281408997)), without encountering the error you report. 

I believe these are the key steps to provision OSX with the prerequisites (assuming MacTeX and homebrew are already installed and updated):

```
brew tap caskroom/fonts
brew cask install font-eb-garamond font-source-code-pro font-lato
sudo tlmgr update --self
sudo tlmgr install biblatex titling titlesec quotchap lettrine appendix units tocloft draftwatermark everypage wasysym logreq xstring collection-fontsrecommended texliveonfly 
```
 
Let me know how you go!

**Comment by mrworthington** [comment]
Hey! So I followed the instructions, but because I already had the fonts and packages loaded, I removed them and reinstalled them.

It allowed me to produce a PDF, but is still reporting errors in the console. The PDF output generally looks good, except that the Table of Contents, Figures, and references pages all have titles with no content. In other words, just blank pages with the titles of each section.

So... I imagine it’s related to the errors reported in the console, but I’ll have to look at it next week and get back to you.

Thanks for the help so far, though! This is a great package!

**Comment by benmarwick** [comment]
Sorry to hear that it's still not quite right for you. When I was testing I also say that problem that you mention. This line installed the packages that solved it for me:

```
sudo tlmgr update --self
sudo tlmgr install biblatex titling titlesec quotchap lettrine appendix units tocloft draftwatermark everypage wasysym logreq xstring collection-fontsrecommended texliveonfly 
```

The PDF I'm getting on OSX looks good, you can see the one generated by Travis-CI here: https://github.com/benmarwick/huskydown/releases/download/0.1.012/thesis.pdf

Feel free to share more of your log file if you'd like help.
