### ISSUE TITLE
Fonts missing from repository

### ISSUE THREAD

**Issue by jflournoy** [benmarwick/huskydown#6]
Thank you for providing this package! In working on modifications for the University of Oregon specifications, I came across the issue that the fonts referenced in the readme are not in the inst directory.

>Our PDF template requires some specific fonts, EB Garamond, Source Code Pro and Lato. These are included in this repository. You need to install these before proceeding, either by using your usual method of installing fonts, or following these instructions

**Comment by benmarwick** [comment]
Yes, currently the fonts are in a top-level fonts.zip directory in the repo

**Comment by benmarwick** [comment]
Yes, good point. At the time you looked, they were in a top level `fonts.zip` file, which didn't match the documentation. I guess I wasn't sure where the best place for them was, and failed to make a clear decision last time I was working on it.  

But in response to your comment, I've shifted the `fonts.zip` into the `inst/` directory so you have them when you install the pkg. 

You'll still need to unzip and install the fonts in the usual way that suits your system. Let me know if you need a hand with  that. I updated the instructions for Linux, but haven't tested them
