### ISSUE TITLE
Committee members not produced

### ISSUE THREAD

**Issue by martinez-jorge** [benmarwick/huskydown#9]
Hello. The rest of my committee was not printed in the following line:

`signature: ["committee member 1", "committee member 2", "committee member 3"]`

I have a total of 3 additional committee members but only the chair is produced. Any ideas on how to fix this? I'm new to the Github universe so please let me know if there is any supporting information I can provide. Thank you.

**Comment by benmarwick** [comment]
Yes, you're right, thanks for pointing that out. I've had a go at fixing it, and now we should get this:

![image](https://user-images.githubusercontent.com/1262179/53232642-5d24a400-3640-11e9-8f66-430b07e14283.png)

Let me know how it works for you (don't forget to update huskydown)

**Comment by martinez-jorge** [comment]
Ben,

Thank you very much - this resolved the issue. I appreciate you creating such a helpful document.
